function set_default_fonts()
% set_default_fonts  AIAA-style groot plotting defaults (Times throughout).
% Call at the top of every figure-producing script; per-figure overrides still apply.
% Sizing: exports (~2000x1400 px / 300 DPI, ~6.67 in wide) shrink ~0.5x into a
% 3.25 in AIAA column, so 16 pt on-screen keeps print at or above the 8 pt minimum.

font_pt   = 16;
title_mul = 18 / font_pt;
legend_pt = 14;
line_pt   = 1.25;
marker_pt = 8;
axes_lw   = 1.0;

set(groot, ...
    'DefaultAxesFontName',                  'Times', ...
    'DefaultAxesFontSize',                  font_pt, ...
    'DefaultAxesTitleFontSizeMultiplier',   title_mul, ...
    'DefaultAxesLabelFontSizeMultiplier',   1.0, ...
    'DefaultAxesLineWidth',                 axes_lw, ...
    'DefaultAxesBox',                       'on', ...
    'DefaultAxesGridAlpha',                 0.25, ...
    'DefaultAxesMinorGridAlpha',            0.15, ...
    'DefaultTextFontName',                  'Times', ...
    'DefaultTextFontSize',                  font_pt, ...
    'DefaultLineLineWidth',                 line_pt, ...
    'DefaultLineMarkerSize',                marker_pt, ...
    'DefaultLegendFontName',                'Times', ...
    'DefaultLegendFontSize',                legend_pt, ...
    'DefaultLegendBox',                     'on', ...
    'DefaultColorbarFontName',              'Times', ...
    'DefaultColorbarFontSize',              legend_pt);

set(groot, ...
    'defaultUicontrolFontName', 'Times', ...
    'defaultUitableFontName',   'Times', ...
    'defaultUipanelFontName',   'Times');
end
